version: '3.7'

services:

  # Accessible at http://localhost:3001
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.front
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - db
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./front:/front

  # Accessible at http://localhost:3000
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev.back
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/web

  # Accessible at http://localhost:8081
  redis-commander:
      image: rediscommander/redis-commander:latest
      environment:
       - REDIS_HOSTS=local:db:6379
      ports:
       - "8081:8081"
      depends_on:
       - db

  # redis://db:6379
  db:
    image: redis
    volumes:
      - db-data:/data

volumes:
  db-data:
