FROM node:11

LABEL "repository"="https://github.com/ib-ai/web"
LABEL "homepage"="https://github.com/ib-ai/web"

WORKDIR /front
RUN rm -rf ./node_modules/
COPY front/package*.json ./

# Building react app
RUN npm install

COPY front/. .

EXPOSE 3001

# Run frontend
CMD ["npm", "start"]
