FROM python:3.8

LABEL "repository"="https://github.com/ib-ai/web"
LABEL "homepage"="https://github.com/ib-ai/web"
LABEL "maintainer"="Jarred Vardy <jarred.vardy@gmail.com>"

WORKDIR /web
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Application entrypoint
CMD [ "python3", "app.py" ]
