version: '3.7'

services:

  # Accessible in network on http://web:3000
  # Public at http://<PUBLIC_HOST>:3000 or http://localhost:3000
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "3000:3000"

  db:
    image: redis
    volumes:
      - db-data:/data

volumes:
  db-data:
